name: PlukEnBlomst
version: ${project.version}
description: This plugin will tell you how much flowers you've harvested
author: Amqlie 
website: http://dev.bukkit.org/server-mods/plukenblomst

main: com.amqlie.plukenblomst.PlukEnBlomst
database: false

commands:
  blomst:
    description: Controls the plukenblomst plugin
    aliases: [flower]
    usage: /blomst

permissions: 
 plukenblomst.*: 
   children: 
     plukenblomst.help: true
   default: false
   description: "Gives access to all plukenblomst commands"