name: PlukEnBlomst
author: Amqlie
version: ${project.version}
api-version: 1.14
website: "http://dev.bukkit.org/server-mods/plukenblomst"
main: com.amqlie.plukenblomst.PlukEnBlomst
commands:
  blomst:
    aliases: [flower]
    description: "Controls the plukenblomst plugin"
    usage: /blomst
permissions: 
  plukenblomst.*: 
    children: 
      plukenblomst.help: true
    default: false
    description: "Gives access to all plukenblomst commands"
